[package]
name = "twitter_watch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
lettre = "0.10.0-rc.4"
reqwest = { version = "0.11.9", features = ["blocking", "json"] }